const Router = require('koa-router')
const multiparty = require('multiparty')
const path = require('path')
const router = new Router();
const { renderHome, renderStaticMain, renderStaticUser, logOut, renderLogin, renderErrorHandler, renderOtherError, mml2latex } = require('./render')
const { upload } = require('./upload')
router
    .get('/', renderHome)
    .get('/item/parse', renderStaticMain)
    .get('/lesson/:edu',renderStaticMain)
    .get('/items/list', renderStaticMain)
    .get('/item/:id', renderStaticMain)
    .get('/item/:id/tag', renderStaticMain)
    .get('/item/:id/typeset', renderStaticMain)
    .get('/item/:id/cluster', renderStaticMain)
    .get('/volume/input', renderStaticMain)
    .get('/volumes', renderStaticMain)
    .get('/volume/:id', renderStaticMain)
    .get('/doc/input', renderStaticMain)
    .get('/doc/:id', renderStaticMain)
    .get('/docs', renderStaticMain)
    .get('/item_search', renderStaticMain)
    .get('/ktags/item_count', renderStaticMain)
    .get('/ktags/', renderStaticMain)
    .get('/ktags/:type', renderStaticMain)
    .get('/textbooks', renderStaticMain)
    .get('/omega_papers', renderStaticMain)
    .get('/omega_paper/:id', renderStaticMain)
    .get('/paper*', renderStaticMain)
    .get('/plan/preview/:id', renderStaticMain)
    .get('/users*', renderStaticUser)
    .get('/profile', renderStaticUser)
    .get('/profile/statistics', renderStaticUser)
    .get('/profile/op_logs/recent', renderStaticUser)
    .get('/auth/logout', logOut)
    .get('/auth/login', renderLogin)
    .get('/admin*', renderStaticUser)
    .post('/api/upload', upload)
    .get('/404', renderErrorHandler)
    .get('/500', renderOtherError)

module.exports =  router